version: '3.9'

services:
  frontend:
    build:
      context: "./Dashboard - vSphere"
      dockerfile: Dockerfile
    image: vsphere-frontend:latest
    container_name: vsphere-frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_SERVER_URL=
      - REACT_APP_API_BASE_URL=/api
    depends_on:
      - backend
    networks:
      - vsphere_net

  backend:
    build:
      context: "./FastAPI - vSphere"
      dockerfile: Dockerfile
    image: vsphere-backend:latest
    container_name: vsphere-backend
    env_file:
      - "./FastAPI - vSphere/.env"
    ports:
      - "8000:8000"
    networks:
      - vsphere_net

networks:
  vsphere_net:
    driver: bridge


